export const RADIUS = 10; 
export const SPACE_X = RADIUS * 2.5;
export const SPACE_Y = RADIUS * 5;
export const STROKE_WIDTH = 1;
export const TIME_GAP = 300;
export const ARROW_ANIMATION_MS = 10;
export const ARROW_ANIMATION_FRAME = 60;
export const NODE_SLEEP_MS = 100;
export const ARROW_SLEEP_TIME = ARROW_ANIMATION_FRAME*ARROW_ANIMATION_MS+500;